//Serialization/Deserialzation of nested map to json string
//https://stackoverflow.com/a/51221692/761902
Map.prototype.toJSON = function() {
  return ['window.Map', Array.from(this.entries())];
};

//Serialization and Deserialization of Map to/from JSON string
function serializeMap(m) {
  return JSON.stringify(m);
}

function deserializeMapString(ms) {
  if (!ms)
    return null;

  //Array is passed. Can either be a plain array or array that is a map (generated by JSON.stringify)
  function arrayToMap(inputArray) {
      if (inputArray[0] == 'window.Map') //This array is representing a stringified map
      return mapArrayToMap(inputArray[1])
      else //A normal array with data, return it as the value
      return inputArray
  }

  //map is passed in as array where each item in the array is another array of size two [0]=key, [1]=value
  function mapArrayToMap(inputMapArray) {
      var retMap = new Map()
      inputMapArray.forEach((v) => {
      retMap.set(v[0], v[1] instanceof Array ? arrayToMap(v[1]): v[1])
      })
      return retMap
  }

  try {
    return arrayToMap(JSON.parse(ms))
  } catch (e) {
    console.log(e)
    return null
  }

  
  }
